version: '3'
services: 
  frontend: 
    build: ./
    ports: 
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true

  